services:
  postgres:
    image: ankane/pgvector
    container_name: triage-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    container_name: triage-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_storage:/root/.ollama