-- CATEGORY 1: TECHNICAL SUPPORT & LOGIN (1-25)
INSERT INTO support_tickets (original_message, sentiment, priority, summary, requires_human, ai_suggested_response) VALUES
        ('Cannot access my account, getting 404 error.', 'NEUTRAL', 'HIGH', '404 Login Error', false, 'Please check your internet connection and ensure the URL is correct. Try clearing your browser cache.'),
        ('Password reset link is expired immediately.', 'ANGRY', 'MEDIUM', 'Password Link Issue', false, 'Password reset links are valid for 15 minutes. Please request a new one and use it immediately.'),
        ('Two-factor authentication code not arriving via SMS.', 'NEUTRAL', 'HIGH', '2FA SMS Failure', true, 'There might be a delay with the telecom provider. I am escalating this to security to provide an alternative verification method.'),
        ('My dashboard is not loading the latest charts.', 'NEUTRAL', 'LOW', 'Dashboard UI Bug', false, 'Try hard refreshing your browser (Ctrl+F5). If the issue persists, our team is likely performing a scheduled sync.'),
        ('The mobile app crashes every time I open the settings.', 'ANGRY', 'MEDIUM', 'App Crash', true, 'We apologize for the crash. Please share your device model and OS version so our mobile team can investigate the logs.'),
        ('How do I enable dark mode on the desktop app?', 'NEUTRAL', 'LOW', 'UI Preference', false, 'Go to Appearance Settings and toggle the Dark Mode switch.'),
        ('Received a "Session Expired" message while typing a long post.', 'ANGRY', 'MEDIUM', 'Session Timeout', false, 'For security, sessions expire after 2 hours of inactivity. We recommend saving drafts frequently.'),
        ('Is your API compatible with Python 3.12?', 'NEUTRAL', 'LOW', 'API Compatibility', false, 'Yes, our latest SDK supports Python 3.10 and above, including 3.12.'),
        ('I found a bug in the search filter, it misses some results.', 'NEUTRAL', 'MEDIUM', 'Search Bug', true, 'Thank you for reporting. Could you provide the specific search term that failed? Our backend team will check the index.'),
        ('The PDF export contains garbled characters.', 'NEUTRAL', 'MEDIUM', 'Export Encoding Issue', false, 'This is usually an encoding issue with special characters. Ensure you have the latest font pack installed or try exporting as CSV.'),
        ('Cannot upload a profile picture, says file too large.', 'NEUTRAL', 'LOW', 'Upload Limit', false, 'The maximum file size for profile pictures is 5MB. Please compress your image and try again.'),
        ('My account was logged out on all devices suddenly.', 'ANGRY', 'HIGH', 'Security Alert', true, 'This happens if a password change is detected or a security breach is suspected. I am locking your account for safety.'),
        ('Where can I find my API key?', 'NEUTRAL', 'LOW', 'API Key Location', false, 'Your API keys are located in the Developer Portal under the "API Keys" tab.'),
        ('Integration with Zapier is failing with a 401 error.', 'NEUTRAL', 'HIGH', 'Integration 401', false, 'A 401 error means "Unauthorized". Please regenerate your API token and update it in Zapier.'),
        ('The website is very slow in the European region.', 'NEUTRAL', 'MEDIUM', 'Regional Latency', true, 'We are investigating a possible CDN issue in Europe. Our team is working on rerouting traffic.'),
        ('I get a "Database Connection Error" intermittently.', 'ANGRY', 'CRITICAL', 'Database Latency', true, 'This is a known issue we are currently fixing. Your data is safe; the connection will be restored shortly.'),
        ('Can I use a hardware security key for login?', 'NEUTRAL', 'LOW', 'FIDO2 Support', false, 'Yes, we support YubiKey and other FIDO2 compliant hardware keys in the Security settings.'),
        ('The "Remember Me" checkbox doesn''t seem to work.', 'NEUTRAL', 'LOW', 'Cookie Issue', false, 'Please ensure your browser is not set to clear cookies on exit.'),
        ('Is there a CLI tool for your platform?', 'NEUTRAL', 'LOW', 'CLI Availability', false, 'Yes, you can install our CLI via npm: npm install -g platform-cli.'),
        ('Error code 500 when saving my profile updates.', 'ANGRY', 'HIGH', 'Internal Server Error', true, 'We noticed a spike in 500 errors. Our engineers are on it. Please try again in 10 minutes.'),
        ('How do I whitelist your IP addresses in my firewall?', 'NEUTRAL', 'MEDIUM', 'Network Whitelisting', false, 'Our outbound IP range is available at /api/v1/ips. Please whitelist these for webhook traffic.'),
        ('Browser says your SSL certificate is invalid.', 'ANGRY', 'CRITICAL', 'SSL Issue', true, 'This is an urgent security matter. We are renewing the certificate immediately. Thank you for the alert.'),
        ('The CAPTCHA is too difficult to solve.', 'NEUTRAL', 'LOW', 'Accessibility', false, 'We offer an audio CAPTCHA option for accessibility. Click the "headphone" icon to use it.'),
        ('Can I change my username?', 'NEUTRAL', 'LOW', 'Username Change', true, 'Usernames can only be changed once per year. An agent will help you process this manually.'),
        ('The platform is down for maintenance, how long will it take?', 'NEUTRAL', 'MEDIUM', 'Maintenance Window', false, 'Scheduled maintenance usually lasts 30 minutes. Check status.example.com for live updates.');

-- CATEGORY 2: BILLING & SUBSCRIPTIONS (26-50)
INSERT INTO support_tickets (original_message, sentiment, priority, summary, requires_human, ai_suggested_response) VALUES
        ('I want a refund for my last transaction.', 'NEUTRAL', 'MEDIUM', 'Refund Request', true, 'I have initiated a refund request. A billing agent will review the transaction and process it within 3-5 business days.'),
        ('Why was I charged $49 instead of $29?', 'ANGRY', 'HIGH', 'Overcharging Complaint', true, 'I apologize for the confusion. It seems like a pro-rated charge from your plan upgrade. I am forwarding this to billing for a detailed breakdown.'),
        ('Can I get an invoice for my January payment?', 'NEUTRAL', 'LOW', 'Invoice Request', false, 'You can download all your invoices directly from the Settings > Billing > History section of your profile.'),
        ('My subscription plan did not renew automatically.', 'NEUTRAL', 'MEDIUM', 'Subscription Renewal Failure', false, 'Please verify that your credit card has not expired. You can update your payment method in the billing tab.'),
        ('I want to cancel my subscription immediately.', 'ANGRY', 'HIGH', 'Cancellation', true, 'We are sorry to see you go. I have set your subscription to "Pending Cancellation". An agent will finalize this and confirm your data deletion options.'),
        ('Does the Pro plan include team collaboration features?', 'NEUTRAL', 'LOW', 'Plan Features', false, 'Yes, the Pro plan includes up to 5 team members and shared workspaces.'),
        ('My payment was declined but my bank says it was successful.', 'ANGRY', 'HIGH', 'Payment Discrepancy', true, 'This is likely a "pending authorization" that will be reversed. I am checking our payment gateway logs right now.'),
        ('Do you offer a student discount?', 'POSITIVE', 'LOW', 'Educational Discount', false, 'Yes! Please send a photo of your student ID to our billing team to receive a 50% discount code.'),
        ('Can I pay with Bitcoin or Ethereum?', 'NEUTRAL', 'LOW', 'Crypto Payment', false, 'Currently, we only accept major credit cards and PayPal. We are considering crypto for the future.'),
        ('Is there a discount for annual billing?', 'POSITIVE', 'LOW', 'Annual Discount', false, 'Yes, paying annually saves you 20% compared to monthly billing.'),
        ('How do I remove my credit card from the system?', 'NEUTRAL', 'MEDIUM', 'Payment Data Removal', true, 'You can remove your card if there is no active subscription. Let me assist you in clearing the data safely.'),
        ('I received an email about a failed payment but my card is fine.', 'NEUTRAL', 'MEDIUM', 'Payment Notification', false, 'This might be a temporary gateway error. Our system will retry the charge automatically in 24 hours.'),
        ('Can I switch from the Pro plan back to the Basic plan?', 'NEUTRAL', 'LOW', 'Downgrade Request', false, 'You can downgrade at the end of your current billing cycle via the Subscription settings.'),
        ('The tax on my invoice seems incorrect for my region.', 'NEUTRAL', 'MEDIUM', 'Tax Issue', true, 'Tax rates are calculated based on your billing address. I will have our finance team review this for you.'),
        ('My company needs a VAT-compliant invoice.', 'NEUTRAL', 'MEDIUM', 'VAT Invoice', false, 'Please update your Business Profile with your VAT ID, and all future invoices will be generated with it.'),
        ('I am being charged for 10 seats but I only use 5.', 'ANGRY', 'MEDIUM', 'Seat Management', false, 'You can reduce your seat count in the Team Management tab to stop being charged for unused seats.'),
        ('Is there a free trial for the Enterprise plan?', 'POSITIVE', 'LOW', 'Enterprise Trial', true, 'Enterprise trials require a quick demo with our sales team. I will schedule a call for you.'),
        ('I was charged twice for the same month.', 'ANGRY', 'CRITICAL', 'Double Billing', true, 'This is a serious error. I have flagged this for immediate refund. You will see the credit in 2 days.'),
        ('Do you offer non-profit discounts?', 'POSITIVE', 'LOW', 'Non-profit Discount', false, 'Yes, we love supporting NGOs! Contact us with your 501(c)(3) documentation for a special rate.'),
        ('Can I use one subscription for multiple organizations?', 'NEUTRAL', 'LOW', 'Multi-Org Billing', false, 'Each organization requires its own separate subscription plan.'),
        ('My payment failed because of 3D Secure.', 'NEUTRAL', 'MEDIUM', '3D Secure Error', false, 'Please ensure your bank''s mobile app is ready to authorize the transaction when the popup appears.'),
        ('Why is there a $1 charge on my statement?', 'NEUTRAL', 'LOW', 'Auth Hold', false, 'That is a temporary authorization hold to verify your card. It will disappear in a few days.'),
        ('I forgot to cancel my trial and was charged.', 'ANGRY', 'MEDIUM', 'Trial Refund', true, 'We understand! As long as you haven''t used the service since the charge, we can process a one-time courtesy refund.'),
        ('Can I get a custom quote for 500 users?', 'NEUTRAL', 'HIGH', 'Bulk Pricing', true, 'For 500+ users, we offer high-volume discounts. I am connecting you with our account executive.'),
        ('My billing cycle starts on the 15th, can I change it to the 1st?', 'NEUTRAL', 'LOW', 'Billing Date Change', false, 'Currently, billing dates cannot be changed, but we can reset your cycle by re-subscribing on the 1st.');

-- CATEGORY 3: FEATURE REQUESTS & FEEDBACK (51-75)
INSERT INTO support_tickets (original_message, sentiment, priority, summary, requires_human, ai_suggested_response) VALUES
        ('Do you have a dark mode available?', 'POSITIVE', 'LOW', 'Dark Mode Feature', false, 'Dark mode is currently in development! We expect to release it in the next major update.'),
        ('Is there a mobile app for Android?', 'NEUTRAL', 'LOW', 'Mobile App Availability', false, 'Yes, you can download our official app from the Google Play Store.'),
        ('How can I export my data to CSV?', 'NEUTRAL', 'LOW', 'Data Export Request', false, 'Go to Reports, select your date range, and click the Export button at the top right corner.'),
        ('I would love to see a Slack integration.', 'POSITIVE', 'LOW', 'Slack Integration Request', false, 'Thank you for the suggestion! We have added Slack integration to our product roadmap.'),
        ('Can I integrate this with Microsoft Teams?', 'NEUTRAL', 'LOW', 'Teams Integration', false, 'We currently support Slack, but Teams integration is planned for Q3 of this year.'),
        ('The font size in the editor is too small for me.', 'NEUTRAL', 'LOW', 'Accessibility Feedback', false, 'You can increase the font size in Settings > Editor > Display.'),
        ('Is there an offline mode for the desktop app?', 'NEUTRAL', 'LOW', 'Offline Support', false, 'Currently, the app requires an internet connection, but we are working on local caching features.'),
        ('I wish there was a way to bulk-edit tickets.', 'POSITIVE', 'MEDIUM', 'Bulk Edit Feature', false, 'Great news! Bulk editing is available. Select multiple tickets and click the "Edit" button in the top bar.'),
        ('Can you add a way to tag users in comments?', 'POSITIVE', 'LOW', 'Mentions Feature', false, 'You can already tag users using @username in any comment!'),
        ('The dashboard colors are hard to read for colorblind users.', 'NEUTRAL', 'HIGH', 'Accessibility', true, 'Thank you for this critical feedback. We are implementing a "Colorblind Mode" immediately.'),
        ('I want a feature to schedule posts in advance.', 'NEUTRAL', 'MEDIUM', 'Scheduling Feature', false, 'Scheduling is available for Pro users. Click the arrow next to "Post" to see scheduling options.'),
        ('Is it possible to have a public status page?', 'NEUTRAL', 'LOW', 'Status Page', false, 'Yes, you can enable a public status page in the Business settings.'),
        ('The mobile app is missing the analytics tab.', 'NEUTRAL', 'MEDIUM', 'Mobile Feature Parity', true, 'Mobile analytics are coming next month. We are currently in the final testing phase.'),
        ('Can we get a Turkish language option?', 'POSITIVE', 'LOW', 'Localization', false, 'Bizim için harika olur! Turkish language support is on our roadmap for next year.'),
        ('I need a way to auto-archive old tickets.', 'NEUTRAL', 'LOW', 'Automation Request', false, 'You can set up an "Auto-Archive" rule in Settings > Workflows.'),
        ('The search feature should support regex.', 'NEUTRAL', 'LOW', 'Power User Feature', false, 'Regex search is currently only available via our API for advanced filtering.'),
        ('Can I change the background image of my profile?', 'POSITIVE', 'LOW', 'Personalization', false, 'Profile backgrounds are a planned feature for our upcoming "Social" update.'),
        ('I hate the new layout, please bring back the old one.', 'ANGRY', 'LOW', 'UI Feedback', true, 'We value your feedback. While we can''t revert, I will pass your specific complaints to the design team.'),
        ('The notifications are too loud/frequent.', 'NEUTRAL', 'LOW', 'Notification Fatigue', false, 'You can customize your notification frequency in Settings > Notifications.'),
        ('Can you add an export to PDF feature?', 'POSITIVE', 'LOW', 'Export Request', false, 'PDF export is already available for Reports. Look for the PDF icon next to the Export button.'),
        ('Is there a way to see who viewed my profile?', 'NEUTRAL', 'LOW', 'Privacy Feature', false, 'For privacy reasons, we do not track or display who visits your profile.'),
        ('I want a Google Calendar integration.', 'POSITIVE', 'LOW', 'Calendar Integration', false, 'Google Calendar sync is available! Check the "Integrations" page to set it up.'),
        ('The API should return JSON instead of XML.', 'NEUTRAL', 'MEDIUM', 'API Feedback', false, 'Our API supports both! Just set the "Accept" header to "application/json" in your request.'),
        ('Can I create my own custom themes?', 'POSITIVE', 'LOW', 'Custom Themes', false, 'Custom CSS themes are available for Enterprise users.'),
        ('Is there a way to recover deleted tickets?', 'NEUTRAL', 'HIGH', 'Data Recovery', true, 'Deleted tickets are kept in the "Trash" for 30 days. Let me help you restore them.');

-- CATEGORY 4: SECURITY & CRITICAL COMPLAINTS (76-100)
INSERT INTO support_tickets (original_message, sentiment, priority, summary, requires_human, ai_suggested_response) VALUES
        ('I am reporting a security vulnerability I found.', 'NEUTRAL', 'CRITICAL', 'Security Vulnerability', true, 'Thank you for your responsible disclosure. Our security team has been notified and will contact you via your encrypted email immediately.'),
        ('This is the third time I am asking for help and NO ONE IS ANSWERING!', 'ANGRY', 'HIGH', 'Escalated Complaint', true, 'I sincerely apologize for the delay. I am personally escalating this ticket to the Support Manager for immediate resolution.'),
        ('My account was hacked and my data is being deleted!', 'ANGRY', 'CRITICAL', 'Account Compromised', true, 'IMMEDIATE ACTION TAKEN: Your account has been temporarily frozen to prevent further loss. Our security lead will call you shortly.'),
        ('Your latest update broke my entire workflow. I am leaving your platform.', 'ANGRY', 'HIGH', 'Churn Risk', true, 'We are truly sorry to hear this. A senior account manager is being assigned to your case to see how we can make this right.'),
        ('I found my private data on a public search engine.', 'ANGRY', 'CRITICAL', 'Data Leak', true, 'This is an urgent privacy matter. I am initiating an immediate audit of your profile visibility settings.'),
        ('I suspect an employee is accessing my private files.', 'ANGRY', 'CRITICAL', 'Insider Threat', true, 'We take this very seriously. Our compliance team is initiating a forensic audit of all access logs for your account.'),
        ('The system is allowing me to see someone else''s tickets.', 'ANGRY', 'CRITICAL', 'IDOR Bug', true, 'CRITICAL SECURITY BREACH: Please stop all activity. Our engineering team is patching this permissions bug right now.'),
        ('I need a GDPR Data Processing Agreement signed.', 'NEUTRAL', 'MEDIUM', 'GDPR Compliance', false, 'You can download our standard DPA from the Legal section of our website for electronic signature.'),
        ('Someone is using my stolen credit card on your platform.', 'ANGRY', 'HIGH', 'Fraud Report', true, 'We have flagged the fraudulent account. Please have your bank contact our legal team to finalize the chargeback.'),
        ('Your app is asking for too many permissions on my phone.', 'NEUTRAL', 'MEDIUM', 'Privacy Concern', false, 'We only ask for camera access for QR scanning. You can deny other permissions in your phone settings.'),
        ('I want to export all my personal data as per CCPA.', 'NEUTRAL', 'MEDIUM', 'Data Portability', true, 'Certainly. I will trigger a full data export for your account. You will receive a ZIP file within 48 hours.'),
        ('Is my data encrypted at rest?', 'NEUTRAL', 'LOW', 'Encryption Inquiry', false, 'Yes, all user data is encrypted at rest using AES-256 encryption.'),
        ('I received a phishing email that looks like it came from you.', 'ANGRY', 'HIGH', 'Phishing Report', true, 'Thank you for the alert! Please forward the email to security@example.com so we can take down the malicious site.'),
        ('Why is my IP address being blocked?', 'ANGRY', 'MEDIUM', 'IP Block', true, 'Our firewall detected multiple failed login attempts from your IP. I can whitelist it after a security verification.'),
        ('Can you provide a SOC2 Type II report?', 'NEUTRAL', 'MEDIUM', 'Compliance Request', true, 'Our latest SOC2 report is available for Enterprise customers under an NDA. I will start the process for you.'),
        ('I noticed an unauthorized login from Russia.', 'ANGRY', 'CRITICAL', 'Unauthorized Access', true, 'Action Taken: I have terminated all active sessions. Please change your password and enable 2FA immediately.'),
        ('How long do you keep my data after I delete my account?', 'NEUTRAL', 'LOW', 'Data Retention', false, 'We purge all identifiable data 30 days after account deletion, except for legal compliance records.'),
        ('Your terms of service changed and I don''t agree.', 'ANGRY', 'MEDIUM', 'TOS Dispute', true, 'An agent will discuss your concerns and help you understand the changes or assist with account closure.'),
        ('Someone is impersonating our brand on your site.', 'ANGRY', 'HIGH', 'Impersonation', true, 'Please provide the links to the profiles. Our trust and safety team will take down verified impersonators.'),
        ('I cannot verify my phone number, the code is always wrong.', 'ANGRY', 'MEDIUM', 'Verification Bug', false, 'Please ensure you are not using a VOIP number, as we only support physical mobile lines for security.'),
        ('Is your data center located in the US or EU?', 'NEUTRAL', 'LOW', 'Data Residency', false, 'We offer regional hosting. You can choose to store your data in our US-East or EU-Central (Frankfurt) regions.'),
        ('I am being harassed by another user.', 'ANGRY', 'CRITICAL', 'Harassment Report', true, 'Safety First: I am blocking the reported user from contacting you while our moderators review their behavior.'),
        ('Your app has a memory leak, it''s using 4GB of RAM.', 'ANGRY', 'MEDIUM', 'Resource Usage', true, 'That sounds like a bug. We are initiating a performance profile on the latest build to find the leak.'),
        ('Can I set up an IP whitelist for my team''s login?', 'NEUTRAL', 'HIGH', 'IP Restricted Login', false, 'Yes, this is an Enterprise feature. You can set authorized IP ranges in the Security Dashboard.'),
        ('I forgot my security questions, I am locked out.', 'ANGRY', 'HIGH', 'Account Recovery', true, 'For security questions, we need to verify your identity via a video call or government ID. An agent will guide you.');